apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebcalculator-deployment
  labels:
    app: javawebcalculator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javawebcalculator
  template:
    metadata:
      labels:
        app: javawebcalculator
    spec:
      containers:
        - name: javawebcalculator
          image: vmns/cicd
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javawebcalculator-service
spec:
  selector:
    app: javawebcalculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: javawebcalculator-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /onlinebookstore/$1
spec:
  ingressClassName: javawebcalculator
  rules:
  - host: www.onlbookst.com
    http:
      paths:
      - path: /?(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: javawebcalculator-service
            port:
              number: 8080
